export const PII_PATTERNS = {
  EMAIL: /[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/g,
  PHONE: /(?:\+?\d{1,3}[-.\s]?)?\(?\d{2,4}\)?[-.\s]?\d{3,4}[-.\s]?\d{4,9}/g,
  IBAN: /[A-Z]{2}\d{2}[A-Z0-9]{12,30}/g,
  CREDIT_CARD: /(?:\d[ -]?){13,19}\d/g,
  VAT_ID:
    /(?:AT|BE|BG|CY|CZ|DE|DK|EE|EL|ES|FI|FR|HR|HU|IE|IT|LT|LU|LV|MT|NL|PL|PT|RO|SE|SI|SK)\s?[0-9A-Z]{2,12}/g,
  TAX_ID: /(?:\b\d{3}-\d{2}-\d{4}\b|\b\d{9}\b|\b[A-Z]{1}\d{7}[A-Z0-9]{1}\b)/g,
  DATE: /\b\d{1,2}[-/.]\d{1,2}[-/.]\d{2,4}\b|\b\d{4}[-/.]\d{1,2}[-/.]\d{1,2}\b/g,
};

export const CONTEXT_LABELS = {
  PERSON_NAME: [
    'name',
    'full name',
    'customer',
    'client',
    'employee',
    'recipient',
    'attention',
    'attn',
  ],
  ADDRESS: [
    'address',
    'billing address',
    'shipping address',
    'residence',
    'location',
    'street',
  ],
  BANK_ACCOUNT: [
    'account',
    'bank account',
    'account number',
    'acc num',
    'iban',
    'bic',
    'swift',
    'sort code',
  ],
  DOB: ['birth date', 'date of birth', 'dob', 'born on'],
  ID_NUMBER: [
    'passport',
    'national id',
    'customer id',
    'client id',
    'employee id',
    'id number',
    'ssn',
    'reference',
  ],
};

export const KEYWORDS = [
  'invoice',
  'contract',
  'receipt',
  'statement',
  'tax',
  'agreement',
  'report',
  'resume',
  'cv',
  'date',
  'total',
  'amount',
  'issuer',
  'reference',
  'customer',
  'vendor',
  'client',
  'recipient',
  'due date',
  'invoice number',
  'account',
];
